travis:
  secure:
    BINSTAR_TOKEN: fC1D2NWpn7JrzupQy3DLOqryAS5kEga/9fjLs7lLfaHjVipmxMjsMhYMFhtzdOl6kEp0rqqiCHy3vAmaDOV+ad1m0lcRXpG5LIRFx5IBtnOjAa6kpm5KOaYYBApCBTBxYF51+XC875YKEPHp2W14SnoiTYlxMcjFJ+DgQ7WUTbnFrwQN64X0MZ66monlXAXm8lnuCLMr5XqDDf1GY/k6ca6Aa0OeQz6luyGFRb+Yw3LwFLSEby/XO55CDSxhEVWpLADOLeYZcty49X/YgUmy3dCGDCR+cR6px47zLZUkUAW3FoUU8qcjJPn+AecvZ1qplaWM5HgzQNNgH+gk9chqNEwYKKxrLrG7j0uO3OLki48SX9ZaupQn4IZzvmTG6H/MtJ6+x+iDeIlTEjvXWjs8nLhYoRxu54lBrI2s026z8HQQNXmpwlJUxzxqX0TNfAnCM1ccTCzRsfzFR95LT3TxpXbWaesPxv0Fyb6p4NmBVd47jnNKJJaHK5kVnKZFldT8TN7+4AW5Ou5fJqrTW3dSv9yrAbEjDR8+Jx0sbo0eDG0kT56xf6DWLvmF+7U/60S3PnFFDhIqQq6gx/yqQfklsWJh0hr35CrsWMP6c+a80ptlrmhIoAdCMaEbmYvaPQxRNyBd6KpoDG6MjUelGqpVMYLqGPZyvTQqheXauRhRC1Q=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
